import {KEY,yen,currentMonth,monthIndex,cost,activePayment,totals,guessCategory,safeUrl,validate,readBackup,extractProduct} from './model.js';
const $=s=>document.querySelector(s),form=$('#item-form'),editor=$('#editor');
let items=[],tab='products',editing=null,loadError=false,request=null;
const field=name=>form.elements.namedItem(name);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
try{const raw=localStorage.getItem(KEY);if(raw)items=readBackup(raw);}catch{loadError=true;$('#save-status').textContent='保存データを読み込めません';}
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4500);}
function commit(next){try{localStorage.setItem(KEY,JSON.stringify({version:1,items:next}));items=next;loadError=false;$('#save-status').textContent='このブラウザに保存済み';render();return true;}catch{toast('保存できません。ブラウザの保存容量や設定を確認してください。');return false;}}
function render(){
  const t=totals(items);$('#total').textContent=yen(t.total);$('#total-detail').textContent=`購入予定 ${t.count}点 · 手数料を含む`;$('#fixed').textContent=yen(t.fixed);$('#planned').innerHTML=`${yen(t.after)}<em>/ 月</em>`;
  $('#sub-total').textContent=yen(t.subscriptions);$('#active-total').textContent=yen(t.active);$('#plan-total').textContent=yen(t.planned);$('#once-total').textContent=yen(t.once);
  $('#product-count').textContent=items.filter(i=>i.kind==='product').length;$('#subscription-count').textContent=items.filter(i=>i.kind==='subscription').length;
  const categories=[...new Set(items.map(i=>i.category))].sort((a,b)=>a.localeCompare(b,'ja'));const selected=$('#category-filter').value;
  $('#category-filter').innerHTML='<option value="all">すべてのカテゴリー</option>'+categories.map(c=>`<option value="${escape(c)}">${escape(c)}</option>`).join('');$('#category-filter').value=categories.includes(selected)?selected:'all';
  $('#categories').innerHTML=[...new Set(['ガジェット','カメラ','暮らし','ファッション','サービス','その他',...categories])].map(c=>`<option value="${escape(c)}">`).join('');
  const sort=$('#sort').value;let visible=items.filter(i=>i.kind===(tab==='products'?'product':'subscription')&&($('#category-filter').value==='all'||i.category===$('#category-filter').value));
  if(sort==='priority')visible.sort((a,b)=>a.priority-b.priority);if(sort==='price-desc')visible.sort((a,b)=>cost(b).total-cost(a).total);if(sort==='price-asc')visible.sort((a,b)=>cost(a).total-cost(b).total);if(sort==='newest')visible.sort((a,b)=>b.created-a.created);
  $('#list-summary').textContent=`${visible.length}点${$('#category-filter').value==='all'?'':' · '+$('#category-filter').value}`;
  $('#empty').hidden=visible.length>0;$('#empty h2').textContent=items.length?'このリストはまだ空です。':'最初のひとつを、リストに。';$('#empty p').innerHTML=tab==='subscriptions'?'毎月・毎年のサブスクや固定費を登録できます。':'商品のリンクから追加して、<br>価格や月々の支払いをまとめて確認できます。';
  $('#items').innerHTML=visible.map((i,index)=>{
    const c=cost(i),sub=i.kind==='subscription',installment=i.payment==='installment'&&!sub;
    let state=sub?({planned:'契約予定',active:'契約中',done:'解約済み'}[i.status]):({planned:'購入予定',active:'支払い中',done:'支払い完了'}[i.status]);
    if(installment&&i.status==='active'){if(activePayment(i))state=`あと${i.months-(monthIndex(currentMonth())-monthIndex(i.start))}回`;else state=monthIndex(currentMonth())<monthIndex(i.start)?'支払い開始前':'支払い終了';}
    return `<article class="item"><div class="item-icon" aria-hidden="true">${sub?'↻':installment?'≡':'◇'}</div><div><div class="item-name">${i.url?`<a href="${escape(i.url)}" target="_blank" rel="noopener noreferrer">${escape(i.name)} ↗</a>`:escape(i.name)}</div><div class="item-meta"><span>${escape(i.category)}</span><span class="badge ${i.priority===1?'high':''}">${['','優先度 高','優先度 普通','優先度 低'][i.priority]}</span><span>${state}</span></div>${i.note?`<div class="note">${escape(i.note)}</div>`:''}</div><div class="item-price">${yen(sub?c.monthly:c.total)}${sub?'<small>/ 月'+(i.cycle==='yearly'?' · 年払い '+yen(i.price):'')+'</small>':installment?`<small>${yen(c.monthly)} / 月 × ${i.months}回</small>`:'<small>一括払い</small>'}</div><div class="item-actions">${sort==='manual'?`<div class="move-buttons"><button class="icon-button" data-move="-1" data-id="${escape(i.id)}" ${index===0?'disabled':''} aria-label="${escape(i.name)}を上に移動">↑</button><button class="icon-button" data-move="1" data-id="${escape(i.id)}" ${index===visible.length-1?'disabled':''} aria-label="${escape(i.name)}を下に移動">↓</button></div>`:''}<button class="icon-button" data-edit="${escape(i.id)}" aria-label="${escape(i.name)}を編集">⋯</button></div></article>`;
  }).join('');
  $('#items').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditor(items.find(i=>i.id===b.dataset.edit)));
  $('#items').querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const from=visible.findIndex(i=>i.id===b.dataset.id),to=from+Number(b.dataset.move);if(!visible[to])return;const next=[...items],a=next.findIndex(i=>i.id===visible[from].id),z=next.findIndex(i=>i.id===visible[to].id);[next[a],next[z]]=[next[z],next[a]];commit(next);});
}
function updateFields(resetStatus=false){const sub=field('kind').value==='subscription';const old=field('status').value;field('status').innerHTML=(sub?[['planned','契約予定'],['active','契約中'],['done','解約済み']]:[['planned','購入予定'],['active','支払い中'],['done','購入済み・支払い完了']]).map(([v,t])=>`<option value="${v}">${t}</option>`).join('');field('status').value=resetStatus?(sub?'active':'planned'):old;
  $('#product-fields').hidden=sub;$('#subscription-fields').hidden=!sub;const installment=!sub&&field('payment').value==='installment';$('#installment-fields').hidden=!installment;for(const key of ['payment','months','feeType','fee','start'])field(key).disabled=sub||(key!=='payment'&&!installment);field('cycle').disabled=!sub;
  field('start').required=installment&&field('status').value==='active';preview();}
function formItem(){return {id:editing?.id||crypto.randomUUID(),kind:field('kind').value,name:field('name').value.trim(),url:safeUrl(field('url').value.trim()),price:Number(field('price').value),category:field('category').value.trim(),priority:Number(field('priority').value),status:field('status').value,payment:field('payment').value,months:Number(field('months').value)||24,feeType:field('feeType').value,fee:Number(field('fee').value),start:field('start').value,cycle:field('cycle').value,note:field('note').value.trim(),created:editing?.created||Date.now()};}
function preview(){try{const c=cost(formItem());$('#installment-preview').innerHTML=`月々 <strong>${yen(c.monthly)}</strong><small>支払い総額 ${yen(c.total)} · 手数料 ${yen(c.fee)}<br>毎回 ${yen(Math.floor(c.monthly))} を基準に、端数 ${yen(c.total%Number(field('months').value))} をいずれかの請求に加算。</small>`;}catch{$('#installment-preview').textContent='価格・回数を入力すると月額を確認できます。';}}
function openEditor(item){if(loadError){toast('保存データを読み込めなかったため、上書きを止めています。バックアップを読み込んで復旧してください。');return;}editing=item||null;form.reset();$('#form-error').textContent='';$('#fetch-status').textContent='';$('#delete-item').hidden=!item;$('#dialog-title').textContent=item?'アイテムを編集':'アイテムを追加';
  const defaults=item||{kind:tab==='subscriptions'?'subscription':'product',status:tab==='subscriptions'?'active':'planned',priority:2,payment:'once',months:24,fee:0,feeType:'yen',cycle:'monthly',start:''};Object.entries(defaults).forEach(([k,v])=>{const input=field(k);if(input)input.value=String(v);});updateFields();editor.showModal();field('url').focus();}
function closeEditor(){request?.abort();request=null;editor.close();}
$('#add').onclick=$('#empty-add').onclick=()=>openEditor();$('#close-editor').onclick=$('#cancel-editor').onclick=closeEditor;editor.addEventListener('close',()=>{request?.abort();request=null;});
field('kind').onchange=()=>updateFields(true);field('payment').onchange=()=>updateFields();field('status').onchange=()=>updateFields();form.addEventListener('input',preview);
form.onsubmit=e=>{e.preventDefault();try{const item=validate(formItem());if(commit(editing?items.map(i=>i.id===editing.id?item:i):[...items,item])){closeEditor();toast('保存しました');}}catch(error){$('#form-error').textContent=error.message;}};
async function confirmAction(title,body,action){$('#confirm-title').textContent=title;$('#confirm-body').textContent=body;$('#confirm-ok').textContent=action;const d=$('#confirm-dialog');d.returnValue='';d.showModal();return new Promise(resolve=>d.addEventListener('close',()=>resolve(d.returnValue==='ok'),{once:true}));}
$('#delete-item').onclick=async()=>{if(await confirmAction('このアイテムを削除しますか？',editing.name,'削除する')){if(commit(items.filter(i=>i.id!==editing.id))){closeEditor();toast('削除しました');}}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-selected',String(x===b)));render();});
document.querySelectorAll('[role=tab]').forEach(b=>b.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const next=[...document.querySelectorAll('[role=tab]')].find(x=>x!==b);next.click();next.focus();}}));
$('#sort').onchange=$('#category-filter').onchange=render;
$('#fetch-info').onclick=async()=>{
  let url;try{url=safeUrl(field('url').value.trim());if(!url)throw new Error('先にリンクを入力してください。');}catch(e){$('#fetch-status').textContent=e.message;return;}
  request?.abort();const controller=new AbortController();request=controller;const timeout=setTimeout(()=>controller.abort(),35000);$('#fetch-info').disabled=true;$('#fetch-status').textContent='商品情報を確認中…';
  try{
    const params=new URLSearchParams({url,'data.structured.selectorAll':'script[type="application/ld+json"]','data.structured.attr':'text','data.price.selector':'meta[property="product:price:amount"],meta[property="og:price:amount"],meta[itemprop="price"]','data.price.attr':'content','data.currency.selector':'meta[property="product:price:currency"],meta[property="og:price:currency"],meta[itemprop="priceCurrency"]','data.currency.attr':'content'});
    const response=await fetch('https://api.microlink.io/?'+params,{signal:controller.signal});if(!response.ok)throw new Error('取得制限または接続エラー');const result=await response.json();if(result.status!=='success')throw new Error('取得に失敗');
    if(request!==controller||!editor.open||field('url').value.trim()!==url&&safeUrl(field('url').value.trim())!==url)return;
    const product=extractProduct(result.data||{});if(product.name&&!field('name').value)field('name').value=product.name;if(product.price!==null&&!field('price').value)field('price').value=String(product.price);if(!field('category').value)field('category').value=guessCategory(product.name+' '+url);
    $('#fetch-status').textContent=product.price===null?'商品情報を取得しました。円の価格を確認できなかったため、価格を入力してください。':'商品情報を取得しました。構成・税込価格を確認してから保存してください。';preview();
  }catch{if(editor.open)$('#fetch-status').textContent='このページの情報を取得できませんでした。名前と価格を手入力して登録できます。';}
  finally{clearTimeout(timeout);if(request===controller){request=null;$('#fetch-info').disabled=false;}else if(!request)$('#fetch-info').disabled=false;}
};
$('#backup').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exported:new Date().toISOString(),items},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`wishlist-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#restore').onclick=()=>$('#restore-file').click();$('#restore-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10000000)throw new Error('10MB以下のファイルを選んでください。');const next=readBackup(await file.text());if(await confirmAction('バックアップを読み込みますか？',`現在の${items.length}点を、バックアップの${next.length}点で置き換えます。`,'読み込む')){if(commit(next))toast('バックアップを読み込みました');}}catch(error){toast(error.message);}finally{e.target.value='';}};
window.addEventListener('storage',e=>{if(e.key!==KEY)return;try{items=e.newValue?readBackup(e.newValue):[];render();toast('別のタブの変更を反映しました');}catch{toast('別のタブのデータを読み込めませんでした。');}});
render();if(loadError)toast('保存データを読み込めませんでした。バックアップから復旧してください。');
